<?php

namespace app\index\model;

use think\Model;

class BooImg extends Common
{

    //
    protected $pk = 'id';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取图书图片
     *
     * @param $book_id
     *
     * @return array|bool
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function img2book($book_id)
    {
        if (empty($book_id)) {
            return false;
        }
        $data = $this->where('bid', $book_id)->select();
        if ( ! empty($data)) {
            return $data->toArray();
        }

        return false;
    }

}
