<?php

namespace app\index\model;

use think\Exception;
use think\Model;

class Books extends Common
{

    //
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function book()
    {
        $this->hasOne('book', 'pid');
    }

    /**
     * 修改图书状态
     *
     * @param $books_id
     * @param $state
     *
     * @return bool
     * @throws \think\exception\PDOException
     */
    public function upBookState($books_id, $state)
    {
        if (empty($books_id)) {
            return false;
        }

        try {
            $this->save(['state' => $state], ['id' => $books_id]);
            $this->commit();

            return true;
        } catch (Exception $exception) {
            $this->rollback();

            return false;
        }
    }

    /**
     * @param $bname
     *
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function searchBook($bname)
    {
        if (empty($bname)) {
            return false;
        }
        $data = $this->where('name', 'like', '%'.$bname.'%')->select();
//        if ( ! empty($data)) {
//            $books = $data->toArray();
//            // 获取所有书的id
//            $book_ids = "";
//            foreach ($books as $key => $value) {
//                $book_ids .= $value["id"];
//            }
//        }
    }
}
