<?php

namespace app\index\model;

use think\Model;

class Order extends Common
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $uid
     *
     * @return array|bool
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function bought($uid)
    {
        $data = $this->join('books', 'books.id =order.bid ')->where('uid', $uid)
            ->where('order.type', 1)->field(
                'books.name,books.author,books.press,books.number bs_No,order.number order_No,order.amount,order.time'
            )->select();
        if ( ! empty($data)) {
            return $data->toArray();
        }

        return false;
    }


    public function orderInfo(){
    }
}
